name: Azure ETL Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    env:
      SQL_SERVER: ${{ secrets.SQL_SERVER }}
      SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Install ODBC Driver
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
          odbcinst -q -d

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run ETL
        run: python src/etl.py