name: Azure ETL Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run ETL
        run: python src/etl.py
